### ISSUE TITLE
Save As

### ISSUE THREAD

**Issue by BlakCake** [MeltedHeart/progress-tracker#15]
Comparing the current data with the save file and saving only the changed data.
May need to create two separate save files to compare

**Comment by JustwayTD** [comment]
why not directly overwrite the previous save file?

**Comment by BlakCake** [comment]
You are correct. We already save every change the user makes so what we really need is the Save As function

**Comment by JustwayTD** [comment]
save as what exactly

**Comment by BlakCake** [comment]
Save as another program, another save file. Just like it works in MS Office and other apps

**Comment by JustwayTD** [comment]
Now Works in commit c7cb7ad
