### ISSUE TITLE
Fix New File MsgBox

### ISSUE THREAD

**Issue by BlakCake** [MeltedHeart/progress-tracker#19]
Here's the MsgBox

![image](https://user-images.githubusercontent.com/18336899/64231766-1ac50500-ceb6-11e9-879c-60fc82d5018e.png)

Should be like this:

![image](https://user-images.githubusercontent.com/18336899/64231810-2b757b00-ceb6-11e9-8bca-cf63035129cb.png)

**Comment by JustwayTD** [comment]
![image](https://user-images.githubusercontent.com/37579267/64231971-91fa9900-ceb6-11e9-8d9c-017b1a488bb2.png)

**Comment by JustwayTD** [comment]
(As per commit 659a4df) Fixed
