### ISSUE TITLE
Being able to create an empty program

### ISSUE THREAD

**Issue by BlakCake** [MeltedHeart/progress-tracker#7]
Create an empty program when clicking on File > New

**Comment by JustwayTD** [comment]
( As per Commit e72c036) A new file is created.
Left to do,
-Check when the file is being saved that the current file is not a temp file, if it is goto save as
-also, the program needs to read this temp file as it is first ran

**Comment by JustwayTD** [comment]
(As Per commit 7733419) The program now starts with a new file which is a temp one, it has been tested, but there is still a problem in which if the directory is deleted from the settings ini file this gives us a soft error
